services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: researchmind-postgres
    environment:
      POSTGRES_DB: researchmind
      POSTGRES_USER: researchmind
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U researchmind -d researchmind"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - researchmind-network

  redis:
    image: redis:7-alpine
    container_name: researchmind-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - researchmind-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: researchmind-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
      - ./docker/qdrant/config.yml:/qdrant/config/production.yaml
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/6333 && echo -e 'GET /readyz HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && grep -q 'HTTP/1.1 200' <&3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - researchmind-network

  neo4j:
    image: neo4j:latest
    container_name: researchmind-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - researchmind-network

  ollama:
    image: ollama/ollama:latest
    container_name: researchmind-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - researchmind-network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: researchmind-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://researchmind:password@postgres:5432/researchmind
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_HOST=qdrant
      - NEO4J_URI=bolt://neo4j:7687
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - researchmind-network


volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_plugins:
  ollama_data:

networks:
  researchmind-network:
    driver: bridge
