service:
  http_port: 6333
  grpc_port: 6334
  max_request_size_mb: 32

cluster:
  enabled: false

storage:
  optimizers:
    default_segment_number: 2
    flush_interval_sec: 5
    max_optimization_threads: 2

  quantization:
    scalar:
      type: int8
      always_ram: true

hnsw_config:
  m: 16
  ef_construct: 100
  full_scan_threshold: 10000